---
apiVersion: v1
kind: Service
metadata:
    name: website
    namespace: deploy-eks
    labels:
        app: website
spec:
    type: LoadBalancer
    selector:
        app: website
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 3000
